version: '3'
services:
  mysql-standalone:
    image: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=banking1
    ports:
      - "3307:3306"
  banking-account-docker:
    image: banking-account-docker
    ports:
      - "8083:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/banking1?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone